### ISSUE TITLE
Null Pointer exception in Launcher is specific file is set in key, but file does not exist

### ISSUE THREAD

**Issue by swalton00** [griffon-plugins/griffon-preferences-plugin#7]
I set preferences.persistor.location = "rfidProperties.json" in config.groovy, but if the file does not exist, I get an Null Pointer exception. Creating an empty file resolves the issue. It would also be nice to have this documented. 
This is the build.gradle relevant lines:

   compile 'org.codehaus.griffon.plugins:griffon-preferences-json:1.2.0'
    griffon 'org.codehaus.griffon.plugins:griffon-preferences-plugin:1.2.0'

Here's the stacktrace: 
2015-09-28 17:29:48,396 TRACE griffon.util.CompositeResourceBundle main Searching key=preferences.persistor.location
2015-09-28 17:29:48,396 TRACE griffon.util.CompositeResourceBundle main Bundle griffon.util.ExpandableResourceBundle@338c99c8; key=preferences.persistor.location; value='rfidProperties.json'
2015-09-28 17:29:48,396 INFO griffon.plugins.preferences.persistors.AbstractMapBasedPreferencesPersistor main Reading preferences from rfidProperties.json
2015-09-28 17:29:48,398 ERROR griffon.core.GriffonExceptionHandler main Uncaught Exception
java.lang.NullPointerException
    at griffon.plugins.preferences.persistors.AbstractMapBasedPreferencesPersistor.inputStream(AbstractMapBasedPreferencesPersistor.java:70)
    at griffon.plugins.preferences.persistors.JsonPreferencesPersistor.read(JsonPreferencesPersistor.java:55)
    at com.spw.rr.Launcher.main(Launcher.groovy:7)

**Comment by aalmiray** [comment]
The location must be set as an absolute path, that's why the NPE occurs due to

```
file.getParentFile().mkdirs()
       ^---- null !!
```

However the plugin may try to correct this oversight by making the suggested location a child of "user.home".
